### PR TITLE
Fix unbound local var error for APIKeyError

### LINKED ISSUE #16: 'Recommedation' errors
@MLnick - I grabbed the latest, and I'm still having issues with this.

Again, I did NOT install 'tmdbsimple' and skipped the 'optional' step of connecting to the TMDB API. Then when I get to the 'recommendation' steps, they all give me the same error:

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-48-63590843c57d> in <module>()
----> 1 display_similar(1, num=5, q="genres:children")

<ipython-input-45-0d64c89fb4d2> in display_similar(the_id, q, num, index, dt)
    144     """
    145     movie, recs = get_similar(the_id, q, num, index, dt)
--> 146     q_im_url = get_poster_url(movie['tmdbId'])
    147     if q_im_url == "NA":
    148         display(HTML("<i>Cannot import tmdbsimple. No movie posters will be displayed!</i>"))

<ipython-input-45-0d64c89fb4d2> in get_poster_url(id)
     10         poster_url = IMAGE_URL + movie['poster_path'] if 'poster_path' in movie and movie['poster_path'] is not None else ""
     11         return poster_url
---> 12     except APIKeyError as ae:
     13         return "KEY_ERR"
     14     except ModuleNotFoundError as me:

UnboundLocalError: local variable 'APIKeyError' referenced before assignment

Maybe we should make this a MANDATORY step and force the user to figure out how to correctly install tmdbsimple?

### PR DESCRIPTION
**Pull request by MLnick**
Resolves #16

### CODE REVIEW

**Comment by MLnick** [comment]
cc @rhagarty

**Comment by rhagarty** [comment]
This doesn't fix the issue for me. The API-KEY is not the issue, it's:
import tmdbsimple as tmdb

I do not have tmdbsimple installed on my machine. Since loading it is 'optional', we should either 
1) handle it not being there
2) make it mandatory that the user install it

Here are the errors I'm getting related to this -

1) error when performing the optional step to load the tmdb api (which is reasonable error):
NameError                                 Traceback (most recent call last)
<ipython-input-30-d24637a947ae> in <module>()
     10     movie_poster_url = IMAGE_URL + movie_info['poster_path']
     11     display(Image(movie_poster_url, width=200))
---> 12 except ModuleNotFoundError:
     13     print("Cannot import tmdbsimple, no movie posters will be displayed!")

NameError: name 'ModuleNotFoundError' is not defined

2) error in '5(a) find similar' recommended movie:
NameError                                 Traceback (most recent call last)
<ipython-input-48-47e214005d6a> in <module>()
----> 1 display_similar(2628, num=5)

<ipython-input-47-736c4d590601> in display_similar(the_id, q, num, index, dt)
    145     """
    146     movie, recs = get_similar(the_id, q, num, index, dt)
--> 147     q_im_url = get_poster_url(movie['tmdbId'])
    148     if q_im_url == "NA":
    149         display(HTML("<i>Cannot import tmdbsimple. No movie posters will be displayed!</i>"))

<ipython-input-47-736c4d590601> in get_poster_url(id)
     13         except APIKeyError as ae:
     14             return "KEY_ERR"
---> 15     except ModuleNotFoundError as me:
     16         return "NA"
     17 

NameError: global name 'ModuleNotFoundError' is not defined

3) error in '5(b) find movies' recommended movie:
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-51-4124b669db7b> in <module>()
----> 1 display_user_recs(12, num=5, num_last=5)

<ipython-input-47-736c4d590601> in display_user_recs(the_id, q, num, num_last, index)
    103     # check that posters can be displayed
    104     first_movie = user_movies[0]
--> 105     first_im_url = get_poster_url(movie['tmdbId'])
    106     if q_im_url == "NA":
    107         display(HTML("<i>Cannot import tmdbsimple. No movie posters will be displayed!</i>"))

UnboundLocalError: local variable 'movie' referenced before assignment

**Comment by MLnick** [comment]
The 2nd error is a bug - will fix that.

**Comment by MLnick** [comment]
The 1st error is really weird - it is like it can't actually catch the module not found exception.

What environment are you using (Python version etc)?

The only other solution would be to just catch `Exception` there instead.

I'd make the API access mandatory - but I actually sort of forgot that you have to fill in that form and wait for an API key... it is some friction that I worry would deter quite a few potential users. So first prize will be to correctly handle it with no API access.

**Comment by rhagarty** [comment]
I'm using Python 2.7.10
I don't have 3.X installed

**Comment by rhagarty** [comment]
Yeah, you need to handle just `Exception`

exception ModuleNotFoundError
A subclass of ImportError which is raised by import when a module could not be located. It is also raised when None is found in sys.modules.

New in version 3.6.

**Comment by rhagarty** [comment]
def get_poster_url(id):
    """Fetch movie poster image URL from TMDb API given a tmdbId"""
    IMAGE_URL = 'https://image.tmdb.org/t/p/w500'
    try:
        import tmdbsimple as tmdb
        from tmdbsimple import APIKeyError
        try:
            movie = tmdb.Movies(id).info()
            poster_url = IMAGE_URL + movie['poster_path'] if 'poster_path' in movie and movie['poster_path'] is not None else ""
            return poster_url
        except APIKeyError as ae:
            return "KEY_ERR"
    except Exception as ex:
        return "NA"

This fixed the 5(a) recommendation errors for me. I see the movie titles display correctly.

Still get the 5(b) errors.

**Comment by MLnick** [comment]
@rhagarty latest commit should fix the 5(b) errors.

**Comment by MLnick** [comment]
@rhagarty and also pushed commit to use `Exception` instead of `ModuleNotFoundError`.

Hopefully this should all work for you now!

**Pull request merged**
